INSERT INTO signe (signe, romaji, discr) VALUES
('あ', 'a', 'hiragana'),
('い', 'i', 'hiragana'),
('う', 'u', 'hiragana'),
('え', 'e', 'hiragana'),
('お', 'o', 'hiragana'),
('か', 'ka', 'hiragana'),
('き', 'ki', 'hiragana'),
('く', 'ku', 'hiragana'),
('け', 'ke', 'hiragana'),
('こ', 'ko', 'hiragana'),
('さ', 'sa', 'hiragana'),
('し', 'shi', 'hiragana'),
('す', 'su', 'hiragana'),
('せ', 'se', 'hiragana'),
('そ', 'so', 'hiragana'),
('た', 'ta', 'hiragana'),
('ち', 'chi', 'hiragana'),
('つ', 'tsu', 'hiragana'),
('て', 'te', 'hiragana'),
('と', 'to', 'hiragana'),
('な', 'na', 'hiragana'),
('に', 'ni', 'hiragana'),
('ぬ', 'nu', 'hiragana'),
('ね', 'ne', 'hiragana'),
('の', 'no', 'hiragana'),
('は', 'ha', 'hiragana'),
('ひ', 'hi', 'hiragana'),
('ふ', 'fu', 'hiragana'),
('へ', 'he', 'hiragana'),
('ほ', 'ho', 'hiragana'),
('ま', 'ma', 'hiragana'),
('み', 'mi', 'hiragana'),
('む', 'mu', 'hiragana'),
('め', 'me', 'hiragana'),
('も', 'mo', 'hiragana'),
('や', 'ya', 'hiragana'),
('ゆ', 'yu', 'hiragana'),
('よ', 'yo', 'hiragana'),
('ら', 'ra', 'hiragana'),
('り', 'ri', 'hiragana'),
('る', 'ru', 'hiragana'),
('れ', 're', 'hiragana'),
('ろ', 'ro', 'hiragana'),
('わ', 'wa', 'hiragana'),
('を', 'wo', 'hiragana'),
('ん', 'n', 'hiragana'),

('が', 'ga', 'hiragana'),
('ぎ', 'gi', 'hiragana'),
('ぐ', 'gu', 'hiragana'),
('げ', 'ge', 'hiragana'),
('ご', 'go', 'hiragana'),
('ざ', 'za', 'hiragana'),
('じ', 'ji', 'hiragana'),
('ず', 'zu', 'hiragana'),
('ぜ', 'ze', 'hiragana'),
('ぞ', 'zo', 'hiragana'),
('だ', 'da', 'hiragana'),
('ぢ', 'ji', 'hiragana'),
('づ', 'zu', 'hiragana'),
('で', 'de', 'hiragana'),
('ど', 'do', 'hiragana'),
('ば', 'ba', 'hiragana'),
('び', 'bi', 'hiragana'),
('ぶ', 'bu', 'hiragana'),
('べ', 'be', 'hiragana'),
('ぼ', 'bo', 'hiragana'),
('ぱ', 'pa', 'hiragana'),
('ぴ', 'pi', 'hiragana'),
('ぷ', 'pu', 'hiragana'),
('ぺ', 'pe', 'hiragana'),
('ぽ', 'po', 'hiragana'),

('きゃ', 'kya', 'hiragana'),
('きゅ', 'kyu', 'hiragana'),
('きょ', 'kyo', 'hiragana'),
('ぎゃ', 'gya', 'hiragana'),
('ぎゅ', 'gyu', 'hiragana'),
('ぎょ', 'gyo', 'hiragana'),
('しゃ', 'sha', 'hiragana'),
('しゅ', 'shu', 'hiragana'),
('しょ', 'sho', 'hiragana'),
('じゃ', 'ja', 'hiragana'),
('じゅ', 'ju', 'hiragana'),
('じょ', 'jo', 'hiragana'),
('ちゃ', 'cha', 'hiragana'),
('ちゅ', 'chu', 'hiragana'),
('ちょ', 'cho', 'hiragana'),
('にゃ', 'nya', 'hiragana'),
('にゅ', 'nyu', 'hiragana'),
('にょ', 'nyo', 'hiragana'),
('ひゃ', 'hya', 'hiragana'),
('ひゅ', 'hyu', 'hiragana'),
('ひょ', 'hyo', 'hiragana'),
('びゃ', 'bya', 'hiragana'),
('びゅ', 'byu', 'hiragana'),
('びょ', 'byo', 'hiragana'),
('ぴゃ', 'pya', 'hiragana'),
('ぴゅ', 'pyu', 'hiragana'),
('ぴょ', 'pyo', 'hiragana'),
('みゃ', 'mya', 'hiragana'),
('みゅ', 'myu', 'hiragana'),
('みょ', 'myo', 'hiragana'),
('りゃ', 'rya', 'hiragana'),
('りゅ', 'ryu', 'hiragana'),
('りょ', 'ryo', 'hiragana');


INSERT INTO hiragana (id, type) VALUES
(1, 'monogramme'),
(2, 'monogramme'),
(3, 'monogramme'),
(4, 'monogramme'),
(5, 'monogramme'),
(6, 'monogramme'),
(7, 'monogramme'),
(8, 'monogramme'),
(9, 'monogramme'),
(10, 'monogramme'),
(11, 'monogramme'),
(12, 'monogramme'),
(13, 'monogramme'),
(14, 'monogramme'),
(15, 'monogramme'),
(16, 'monogramme'),
(17, 'monogramme'),
(18, 'monogramme'),
(19, 'monogramme'),
(20, 'monogramme'),
(21, 'monogramme'),
(22, 'monogramme'),
(23, 'monogramme'),
(24, 'monogramme'),
(25, 'monogramme'),
(26, 'monogramme'),
(27, 'monogramme'),
(28, 'monogramme'),
(29, 'monogramme'),
(30, 'monogramme'),
(31, 'monogramme'),
(32, 'monogramme'),
(33, 'monogramme'),
(34, 'monogramme'),
(35, 'monogramme'),
(36, 'monogramme'),
(37, 'monogramme'),
(38, 'monogramme'),
(39, 'monogramme'),
(40, 'monogramme'),
(41, 'monogramme'),
(42, 'monogramme'),
(43, 'monogramme'),
(44, 'monogramme'),
(45, 'monogramme'),
(46, 'monogramme'),
(47, 'monogramme/diacritique'),
(48, 'monogramme/diacritique'),
(49, 'monogramme/diacritique'),
(50, 'monogramme/diacritique'),
(51, 'monogramme/diacritique'),
(52, 'monogramme/diacritique'),
(53, 'monogramme/diacritique'),
(54, 'monogramme/diacritique'),
(55, 'monogramme/diacritique'),
(56, 'monogramme/diacritique'),
(57, 'monogramme/diacritique'),
(58, 'monogramme/diacritique'),
(59, 'monogramme/diacritique'),
(60, 'monogramme/diacritique'),
(61, 'monogramme/diacritique'),
(62, 'monogramme/diacritique'),
(63, 'monogramme/diacritique'),
(64, 'monogramme/diacritique'),
(65, 'monogramme/diacritique'),
(66, 'monogramme/diacritique'),
(67, 'monogramme/diacritique'),
(68, 'monogramme/diacritique'),
(69, 'monogramme/diacritique'),
(70, 'monogramme/diacritique'),
(71, 'monogramme/diacritique'),
(72, 'digramme'),
(73, 'digramme'),
(74, 'digramme'),
(75, 'digramme/diacritique'),
(76, 'digramme/diacritique'),
(77, 'digramme/diacritique'),
(78, 'digramme'),
(79, 'digramme'),
(80, 'digramme'),
(81, 'digramme/diacritique'),
(82, 'digramme/diacritique'),
(83, 'digramme/diacritique'),
(84, 'digramme'),
(85, 'digramme'),
(86, 'digramme'),
(87, 'digramme'),
(88, 'digramme'),
(89, 'digramme'),
(90, 'digramme'),
(91, 'digramme'),
(92, 'digramme'),
(93, 'digramme/diacritique'),
(94, 'digramme/diacritique'),
(95, 'digramme/diacritique'),
(96, 'digramme/diacritique'),
(97, 'digramme/diacritique'),
(98, 'digramme/diacritique'),
(99, 'digramme'),
(100, 'digramme'),
(101, 'digramme'),
(102, 'digramme'),
(103, 'digramme'),
(104, 'digramme');
