INSERT INTO signe (signe, romaji, discr) VALUES
('ア', 'a', 'katakana'),
('イ', 'i', 'katakana'),
('ウ', 'u', 'katakana'),
('エ', 'e', 'katakana'),
('オ', 'o', 'katakana'),
('カ', 'ka', 'katakana'),
('キ', 'ki', 'katakana'),
('ク', 'ku', 'katakana'),
('ケ', 'ke', 'katakana'),
('コ', 'ko', 'katakana'),
('サ', 'sa', 'katakana'),
('シ', 'shi', 'katakana'),
('ス', 'su', 'katakana'),
('セ', 'se', 'katakana'),
('ソ', 'so', 'katakana'),
('タ', 'ta', 'katakana'),
('チ', 'chi', 'katakana'),
('ツ', 'tsu', 'katakana'),
('テ', 'te', 'katakana'),
('ト', 'to', 'katakana'),
('ナ', 'na', 'katakana'),
('ニ', 'ni', 'katakana'),
('ヌ', 'nu', 'katakana'),
('ネ', 'ne', 'katakana'),
('ノ', 'no', 'katakana'),
('ハ', 'ha', 'katakana'),
('ヒ', 'hi', 'katakana'),
('フ', 'fu', 'katakana'),
('ヘ', 'he', 'katakana'),
('ホ', 'ho', 'katakana'),
('マ', 'ma', 'katakana'),
('ミ', 'mi', 'katakana'),
('ミ', 'mu', 'katakana'),
('メ', 'me', 'katakana'),
('モ', 'mo', 'katakana'),
('ヤ', 'ya', 'katakana'),
('ユ', 'yu', 'katakana'),
('ヨ', 'yo', 'katakana'),
('ラ', 'ra', 'katakana'),
('リ', 'ri', 'katakana'),
('ル', 'ru', 'katakana'),
('レ', 're', 'katakana'),
('ロ', 'ro', 'katakana'),
('ワ', 'wa', 'katakana'),
('ヲ', 'wo', 'katakana'),
('ン', 'n', 'katakana'),

('ガ', 'ga', 'katakana'),
('ギ', 'gi', 'katakana'),
('グ', 'gu', 'katakana'),
('ゲ', 'ge', 'katakana'),
('ゴ', 'go', 'katakana'),
('ザ', 'za', 'katakana'),
('ジ', 'ji', 'katakana'),
('ズ', 'zu', 'katakana'),
('ゼ', 'ze', 'katakana'),
('ゾ', 'zo', 'katakana'),
('ダ', 'da', 'katakana'),
('ヂ', 'ji', 'katakana'),
('ヅ', 'zu', 'katakana'),
('デ', 'de', 'katakana'),
('ド', 'do', 'katakana'),
('バ', 'ba', 'katakana'),
('ビ', 'bi', 'katakana'),
('ブ', 'bu', 'katakana'),
('ベ', 'be', 'katakana'),
('ボ', 'bo', 'katakana'),
('パ', 'pa', 'katakana'),
('ピ', 'pi', 'katakana'),
('プ', 'pu', 'katakana'),
('ペ', 'pe', 'katakana'),
('ポ', 'po', 'katakana'),

('キャ', 'kya', 'katakana'),
('キュ', 'kyu', 'katakana'),
('キョ', 'kyo', 'katakana'),
('ギャ', 'gya', 'katakana'),
('ギュ', 'gyu', 'katakana'),
('ギョ', 'gyo', 'katakana'),
('シャ', 'sha', 'katakana'),
('シュ', 'shu', 'katakana'),
('ショ', 'sho', 'katakana'),
('ジャ', 'ja', 'katakana'),
('ジュ', 'ju', 'katakana'),
('ジョ', 'jo', 'katakana'),
('チャ', 'cha', 'katakana'),
('チュ', 'chu', 'katakana'),
('チョ', 'cho', 'katakana'),
('ニャ', 'nya', 'katakana'),
('ニュ', 'nyu', 'katakana'),
('ニョ', 'nyo', 'katakana'),
('ヒャ', 'hya', 'katakana'),
('ヒュ', 'hyu', 'katakana'),
('ヒョ', 'hyo', 'katakana'),
('ビャ', 'bya', 'katakana'),
('ビュ', 'byu', 'katakana'),
('ビョ', 'byo', 'katakana'),
('ピャ', 'pya', 'katakana'),
('ピュ', 'pyu', 'katakana'),
('ピョ', 'pyo', 'katakana'),
('ミャ', 'mya', 'katakana'),
('ミュ', 'myu', 'katakana'),
('ミョ', 'myo', 'katakana'),
('リャ', 'rya', 'katakana'),
('リュ', 'ryu', 'katakana'),
('リョ', 'ryo', 'katakana');


INSERT INTO katakana (id, type) VALUES
(105, 'monogramme'),
(106, 'monogramme'),
(107, 'monogramme'),
(108, 'monogramme'),
(109, 'monogramme'),
(110, 'monogramme'),
(111, 'monogramme'),
(112, 'monogramme'),
(113, 'monogramme'),
(114, 'monogramme'),
(115, 'monogramme'),
(116, 'monogramme'),
(117, 'monogramme'),
(118, 'monogramme'),
(119, 'monogramme'),
(120, 'monogramme'),
(121, 'monogramme'),
(122, 'monogramme'),
(123, 'monogramme'),
(124, 'monogramme'),
(125, 'monogramme'),
(126, 'monogramme'),
(127, 'monogramme'),
(128, 'monogramme'),
(129, 'monogramme'),
(130, 'monogramme'),
(131, 'monogramme'),
(132, 'monogramme'),
(133, 'monogramme'),
(134, 'monogramme'),
(135, 'monogramme'),
(136, 'monogramme'),
(137, 'monogramme'),
(138, 'monogramme'),
(139, 'monogramme'),
(140, 'monogramme'),
(141, 'monogramme'),
(142, 'monogramme'),
(143, 'monogramme'),
(144, 'monogramme'),
(145, 'monogramme'),
(146, 'monogramme'),
(147, 'monogramme'),
(148, 'monogramme'),
(149, 'monogramme'),
(150, 'monogramme'),
(151, 'monogramme/diacritique'),
(152, 'monogramme/diacritique'),
(153, 'monogramme/diacritique'),
(154, 'monogramme/diacritique'),
(155, 'monogramme/diacritique'),
(156, 'monogramme/diacritique'),
(157, 'monogramme/diacritique'),
(158, 'monogramme/diacritique'),
(159, 'monogramme/diacritique'),
(160, 'monogramme/diacritique'),
(161, 'monogramme/diacritique'),
(162, 'monogramme/diacritique'),
(163, 'monogramme/diacritique'),
(164, 'monogramme/diacritique'),
(165, 'monogramme/diacritique'),
(166, 'monogramme/diacritique'),
(167, 'monogramme/diacritique'),
(168, 'monogramme/diacritique'),
(169, 'monogramme/diacritique'),
(170, 'monogramme/diacritique'),
(171, 'monogramme/diacritique'),
(172, 'monogramme/diacritique'),
(173, 'monogramme/diacritique'),
(174, 'monogramme/diacritique'),
(175, 'monogramme/diacritique'),
(176, 'digramme'),
(177, 'digramme'),
(178, 'digramme'),
(179, 'digramme/diacritique'),
(180, 'digramme/diacritique'),
(181, 'digramme/diacritique'),
(182, 'digramme'),
(183, 'digramme'),
(184, 'digramme'),
(185, 'digramme/diacritique'),
(186, 'digramme/diacritique'),
(187, 'digramme/diacritique'),
(188, 'digramme'),
(189, 'digramme'),
(190, 'digramme'),
(191, 'digramme'),
(192, 'digramme'),
(193, 'digramme'),
(194, 'digramme'),
(195, 'digramme'),
(196, 'digramme'),
(197, 'digramme/diacritique'),
(198, 'digramme/diacritique'),
(199, 'digramme/diacritique'),
(200, 'digramme/diacritique'),
(201, 'digramme/diacritique'),
(202, 'digramme/diacritique'),
(203, 'digramme'),
(204, 'digramme'),
(205, 'digramme'),
(206, 'digramme'),
(207, 'digramme'),
(208, 'digramme');
